plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

application {
    mainClass = 'com.itsmarsss.Main'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    maven {
        name = 'm2-dv8tion'
        url = 'https://m2.dv8tion.net/releases'
    }
    mavenCentral()
    maven {
        name = 'jfrog-duncte123'
        url = 'https://duncte123.jfrog.io/artifactory/maven'
    }
}

dependencies {
    implementation 'net.dv8tion:JDA:6.3.0'
    implementation 'ch.qos.logback:logback-classic:1.4.12'
    implementation 'org.yaml:snakeyaml:2.3'
    implementation 'com.googlecode.json-simple:json-simple:1.1.1'
    implementation 'org.jsoup:jsoup:1.15.3'
    implementation 'org.mongodb:mongodb-driver-sync:4.7.2'
    implementation 'org.slf4j:slf4j-api:2.0.16'

    testImplementation platform('org.junit:junit-bom:5.11.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

tasks.named('test', Test) {
    useJUnitPlatform()
}

shadowJar {
    archiveBaseName.set('app')
    archiveClassifier.set('all')
    mergeServiceFiles()
}

build.dependsOn shadowJar
